# Generated by Django 5.0.7 on 2024-08-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('intercom_off', models.CharField(blank=True, max_length=10, null=True)),
                ('intercom_res', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(default='0000000000', max_length=10)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('pprs_published', models.PositiveIntegerField(default=0)),
                ('number_of_interns', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
