# Generated by Django 5.0.7 on 2024-08-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$O5Or6DwxjyR3mqTjys00lp$T5baV0Far0F5sZONKKcXAZZWg2wKxzKZW6VmAGZxaCI=', max_length=128),
        ),
    ]
