# Generated by Django 5.0.7 on 2024-08-11 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='number_of_interns',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='pprs_published',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('duration_of_training', models.CharField(max_length=100)),
                ('parent_institution', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
