# Generated by Django 5.0.7 on 2024-08-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$vvzUUDYoTWx12D1X0vpFpf$itiPQy7bV+CfW2h2U2e2UpjuUTx8pTQ2I6fTTUmmJWU=', max_length=128),
        ),
    ]
