# Generated by Django 5.0.7 on 2024-07-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_firstname_member_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='number_of_interns',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='pprs_published',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
