# Generated by Django 5.0.7 on 2024-08-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='conferences_attended',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='number_of_interns',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='pprs_published',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
