# Generated by Django 5.0.7 on 2024-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_conferences_attended_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='pprs_published',
            new_name='bpub',
        ),
        migrations.AddField(
            model_name='member',
            name='cpub',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='jpub',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
