# Generated by Django 5.0.7 on 2024-08-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_phone_number_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='employee_id',
            field=models.CharField(default=0, max_length=10, unique=True),
        ),
    ]
