# Generated by Django 5.0.7 on 2024-08-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_member_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='employee_id',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
